name: Push test results on TestSpace CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}
          token: ${{ secrets.TESTSPACE_TOKEN }}
      - name: Push result to Testspace server
        run: |
          testspace results.xml
        if: always()